/*
 * This source file was generated by the Gradle 'init' task
 */
package com.callv2.manager;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class LibraryTest {

    @Test
    void someLibraryMethodReturnsTrue() {
        assertTrue(true);
    }
}
