name: Deploy to HML

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      imageTag:
        required: true
        type: string
    secrets:
        DOCKER_USERNAME:
          required: true
        DOCKER_PASSWORD:
          required: true

jobs:
    deploy-to-server:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to HML server
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.HML_SERVER_HOST }}
            username: ${{ secrets.HML_DEPLOY_USER }}
            key: ${{ secrets.SECRET_TEST }}
            script: |
              docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
              docker stop dns-manager-hml || true
              docker rm dns-manager-hml || true
              docker run -d --name dns-manager-hml ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --restart always